spring:
  cloud:
    config:
      fail-fast: true
      ##      Eureka
      discovery:
        enable: true
        serviceId: config-server
eureka:
  client:
    serviceUrl:
      defaultZone:
##     éEureka
#      uri: http://localhost:8769

